---
- name : start reporting tool
  hosts: test-server
  vars: 
      process: reporting
  tasks: 
  - name : get reporting tool process id 
    shell : ps aux | grep "{{ process }}"  | grep -v grep |awk '{print $2}'
    register : process_id
  - debug: msg="{{process_id.stdout}}" 

  - name : start reporting tool 
    shell:  cd /home/fuse/ReportingTool/ &&   nohup /home/fuse/java/jdk1.8.0_144/bin/java -jar /home/fuse/ReportingTool/reportingTool-1.0.jar &
    when : process_id.stdout == "" 
...
