---
- name : stop acceptanceBackend 
  hosts: test-server
  gather_facts: false
  vars: 
      process: acceptance
  tasks: 
  - name : get acceptance backend id 
    shell : ps aux | grep "{{ process }}"  | grep -v grep |awk '{print $2}'
    register : process_id
  - debug: msg="{{process_id.stdout}}" 

  - name : stop acceptance backend
    shell:  kill -9 "{{process_id.stdout}}"
    when : process_id.stdout != "" 
...
