---
- name : start mw Bundle 
  hosts: mw
  gather_facts : false
 # vars_files : 
 #  -  /root/system/vars/mwbundle.yml  
    
  tasks: 
  - name : run start (UIG And MW Bundles)
    shell: /home/fuse/fuse-6.2.1/bin/client -r 3 -d 10 -u admin -p admin 'osgi:start "{{ item }}"'

    with_items:
        -  380
        -  381
        -  382
        -  418
...
